/**
 * Radius Monitor Mac Binding
 * Author : Maizil <https://github.com/maizil41>
 */
$(document).ready(function(){makeAllSortable();$("#filterTable").on("keyup",function(){var value=$(this).val().toLowerCase();$("#dataTable tbody tr").filter(function(){$(this).toggle($(this).text().toLowerCase().indexOf(value)>-1)})})});
const planName = new URLSearchParams(window.location.search).get('planName') || '';
document.getElementById('userstatus').addEventListener('change',function(){const status=this.value;window.location.href=`?planName=${planName}&status=${status}`});
function deleteUser(username){if(confirm("Apakah anda yakin ingin menghapus user "+username+"?")){$.ajax({url:"../backend/delete.hotspot.php",type:"GET",data:{id:username},success:function(response){location.reload()},error:function(xhr,status,error){console.error("Terjadi kesalahan:",error)},})}}
function resetuser(username){if(confirm("Apakah anda yakin ingin mereset user "+username+"?")){$.ajax({url:"../backend/reset.php",type:"GET",data:{id:username},success:function(response){location.reload()},error:function(xhr,status,error){console.error("Terjadi kesalahan:",error)},})}}
document.getElementById("deleteSelected").addEventListener("click",function(){const checkboxes=document.querySelectorAll(".delete-checkbox:checked");const selectedUsers=Array.from(checkboxes).map((checkbox)=>checkbox.value);if(selectedUsers.length===0){alert("Tidak ada mac yang dipilih.");return}
if(confirm("Apakah Anda yakin ingin menghapus mac yang dipilih?")){fetch("../backend/delete_selected.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({users:selectedUsers})}).then((response)=>response.json()).then((data)=>{if(data.success){location.reload()}else{alert("Gagal menghapus pengguna.")}}).catch((error)=>console.error("Error:",error))}});document.getElementById("checkAll").addEventListener("change",function(){const checkboxes=document.querySelectorAll(".delete-checkbox");const isChecked=this.checked;checkboxes.forEach((checkbox)=>{checkbox.checked=isChecked})})